# Generated by Django 2.0.4 on 2018-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.TextField(max_length=19)),
                ('expiry', models.DateField(max_length=5)),
                ('security_Code', models.TextField(max_length=4)),
                ('Deposit', models.BooleanField(default=False)),
                ('Deposit_Amount', models.IntegerField(max_length=20)),
            ],
        ),
    ]
