# Generated by Django 2.0.5 on 2018-06-06 00:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0004_auto_20180605_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLine',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('BookingLineId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('departure', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Packages', to='packages.Packages', verbose_name='departureDate')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('BookingId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bookingDate', models.DateTimeField(default=datetime.date(2018, 6, 6))),
                ('bookingType', models.CharField(max_length=50)),
                ('bookingPayment', models.PositiveIntegerField(verbose_name='Payment')),
                ('bookingDeposit', models.PositiveIntegerField(default=0, verbose_name='Payment')),
                ('seatsChosen', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('duration', models.TextField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('totalCost', models.PositiveIntegerField(default=0)),
                ('hotelName', models.CharField(max_length=100)),
            ],
        ),
    ]
