# Generated by Django 2.0.5 on 2018-05-31 11:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLine',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('BookingLineId', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('BookingId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bookingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookingType', models.CharField(max_length=50)),
                ('bookingPayment', models.IntegerField(verbose_name='Payment')),
                ('bookingDeposit', models.IntegerField(verbose_name='Payment')),
                ('seatsChosen', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('duration', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('totalCost', models.IntegerField()),
                ('hotelName', models.CharField(max_length=100)),
            ],
        ),
    ]
