# Generated by Django 2.0.4 on 2018-04-30 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingline',
            name='departureDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 30, 21, 11, 59, 621493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='bookingDeposit',
            field=models.IntegerField(verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='bookingPayment',
            field=models.IntegerField(verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='totalCost',
            field=models.IntegerField(),
        ),
    ]
