# Generated by Django 2.0.5 on 2018-05-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180529_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='Quantity',
        ),
    ]
